import React, { useEffect, useMemo, useRef, useState } from 'react';
import api from './api';
import Form from './components/Form.jsx';
import CoverLetter from './components/CoverLetter.jsx';
import Loading from './components/Loading.jsx';
import ResumeUpload from './components/ResumeUpload.jsx';


function clampWords(text) {
  return text
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean);
}

export default function App() {
  const mainRef = useRef(null);
  const aiRef = useRef(null);
  const aboutRef = useRef(null);
  const pricingRef = useRef(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [coverLetter, setCoverLetter] = useState('');
  const [toast, setToast] = useState(null);
  const [resumeText, setResumeText] = useState('');

  const initialForm = useMemo(
    () => ({
      name: '',
      email: '',
      role: '',
      company: '',
      skills: '',
      experience: '',
      education: ''
    }),
    []
  );

  const [form, setForm] = useState(initialForm);

  useEffect(() => {
    // Force dark theme only
    document.documentElement.dataset.theme = 'dark';
  }, []);

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), 2600);
    return () => clearTimeout(t);
  }, [toast]);

  async function onGenerate() {
    setError('');
    setSuccess('');
    setLoading(true);

    try {
      const payload = {
        name: form.name,
        role: form.role,
        company: form.company,
        skills: form.skills,
        experience: form.experience,
        education: form.education,
        // optional
        resumeText: resumeText || undefined
      };

      // Phase 1 fallback template generation (works without Gemini)
      // If backend is available and Gemini is correctly configured, we’ll still try it.
      const template =
        `Dear Hiring Manager,\n\n` +
        `I am excited to apply for the ${form.role} position at ${form.company}. My experience in ${form.experience} and my skills in ${form.skills} make me a strong match for your team.\n\n` +
        `In my previous work, I have delivered results including: (1) improving performance and outcomes, (2) collaborating across teams, and (3) communicating clearly with stakeholders. I am confident that I can bring the same impact to ${form.company}.\n\n` +
        `I would welcome the opportunity to discuss how my background aligns with your needs. Thank you for your time and consideration.\n\n` +
        `Sincerely,\n` +
        `${form.name}`;

      try {
        const res = await api.post('/generate', payload);
        const aiText = res.data?.coverLetter;
        if (aiText && typeof aiText === 'string' && aiText.trim()) {
          setCoverLetter(aiText.trim());
          setToast({ type: 'success', message: 'Cover letter generated by AI.' });
        } else {
          setCoverLetter(template);
          setToast({ type: 'success', message: 'Cover letter generated (template fallback).' });
        }
      } catch {
        setCoverLetter(template);
        setToast({ type: 'success', message: 'Cover letter generated (template fallback).' });
      }
    } catch (e) {
      const msg = e?.response?.data?.error || e?.message || 'Failed to generate. Please try again.';
      // Don’t hard-fail the UI—show template fallback if Gemini is unreachable.
      setError(msg);
      setToast({ type: 'error', message: 'Gemini generation failed. Using template instead.' });
    } finally {
      setLoading(false);
    }
  }

  async function onCopy() {
    if (!coverLetter.trim()) return;
    try {
      await navigator.clipboard.writeText(coverLetter);
      setSuccess('Copied to clipboard!');
      setToast({ type: 'success', message: 'Copied to clipboard.' });
    } catch {
      setError('Copy failed. Please copy manually.');
      setToast({ type: 'error', message: 'Copy failed.' });
    }
  }

  function onReset() {
    setForm(initialForm);
    setCoverLetter('');
    setResumeText('');
    setError('');
    setSuccess('');
    setToast({ type: 'success', message: 'Form reset.' });
  }

  function onDownloadPDF() {
    // Simple, client-only PDF: uses print-to-PDF via a temporary window.
    // Production apps may use a dedicated PDF generator library.
    const w = window.open('', '_blank');
    if (!w) {
      setError('Popup blocked. Please allow popups to download PDF.');
      setToast({ type: 'error', message: 'Popup blocked.' });
      return;
    }

    const escapeHtml = (s) =>
      (s || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '<')
        .replace(/>/g, '>');

    const words = clampWords(coverLetter).length;

    w.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>Cover Letter</title>
      <style>
        body{font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; padding:40px; color:#111;}
        .box{border:1px solid #e5e7eb; border-radius:14px; padding:28px;}
        h1{font-size:18px; margin:0 0 14px 0;}
        pre{white-space:pre-wrap; word-break:break-word; font-family:inherit; line-height:1.4;}
        .meta{color:#6b7280; font-size:12px; margin-bottom:14px;}
      </style></head><body>
      <div class="box">
        <h1>AI Cover Letter</h1>
        <div class="meta">Word count: ${words}</div>
        <pre>${escapeHtml(coverLetter)}</pre>
      </div>
      <script>setTimeout(()=>{window.print();}, 250);</script>
      </body></html>`);
    w.document.close();
  }

  return (
    <div className="app">
      <header className="topbar">
        <div className="brand">
          <img src="/logo.png" alt="YOUR NOTICE" className="brandLogoImg" />
          <div>
            <div className="brandTitle">YOUR NOTICE</div>
            <div className="brandSubtitle">ATS-friendly cover letters</div>
          </div>
        </div>

        <nav className="topNav">
          <a onClick={() => aiRef.current?.scrollIntoView({ behavior: 'smooth' })}>AI Solutions</a>
          <a onClick={() => aboutRef.current?.scrollIntoView({ behavior: 'smooth' })}>About</a>
          <a onClick={() => pricingRef.current?.scrollIntoView({ behavior: 'smooth' })}>Pricing</a>
          <button
            className="btn btnPrimary navCta"
            type="button"
            onClick={() => mainRef.current?.scrollIntoView({ behavior: 'smooth' })}
          >
            Get Started
          </button>
        </nav>
      </header>

      <section className="hero">
        <div className="heroInner">
          <div className="heroBadge">Beta Version</div>
          <h1 className="heroTitle">Next-gen cover letters
            <br />that get noticed</h1>
          <p className="heroSubtitle">Generate ATS-friendly, personalized cover letters in seconds using AI.</p>
          <div className="heroActions">
            <button className="btn btnPrimary heroCta" onClick={() => mainRef.current?.scrollIntoView({ behavior: 'smooth' })}>Get Started</button>
          </div>
        </div>
      </section>

      <section ref={aiRef} className="section sectionSolutions">
        <div className="containerInner">
          <h2 className="sectionTitle">AI Solutions</h2>
          <p className="sectionLead">Smart templates and personalization powered by AI to tailor cover letters quickly and accurately. We focus on extracting the most relevant achievements from your resume and presenting them in a role-specific, ATS-friendly format.</p>

          <div className="solutionsGrid">
            <div className="solutionCard">
              <h3>Personalization</h3>
              <p>Use resume parsing to surface project highlights, metrics, and keywords so every letter reads as if written for the role.</p>
            </div>
            <div className="solutionCard">
              <h3>ATS Optimization</h3>
              <p>Structure and phrasing are optimized for applicant tracking systems to improve the odds of passing automated screening.</p>
            </div>
            <div className="solutionCard">
              <h3>Tone & Style</h3>
              <p>Choose the voice that fits your application—formal, conversational, or achievement-driven—and adjust length and emphasis.</p>
            </div>
          </div>
        </div>
      </section>

      <section ref={aboutRef} className="section sectionAbout">
        <div className="containerInner">
          <h2 className="sectionTitle">About</h2>
          <p className="sectionLead">Your Notice was created to simplify job applications. We blend prompt-engineered AI and smart resume extraction to generate letters that are concise, relevant, and tailored to hiring managers. Our mission is to help candidates present their best, most relevant selves in fewer minutes.</p>
          <p style={{textAlign: 'center', color: 'var(--muted)', maxWidth: 860, margin: '12px auto 0'}}>Founded by recruiters and engineers, we iterate on feedback from real hiring teams to ensure letters highlight the right mix of impact and fit.</p>
        </div>
      </section>

      <section ref={pricingRef} className="section sectionPricing">
        <div className="containerInner">
          <h2 className="sectionTitle">Pricing</h2>
          <p className="sectionLead">Transparent pricing that scales with your needs—try for free, upgrade for more features, or contact us for enterprise plans.</p>

          <div className="pricingGrid">
            <div className="priceCard">
              <div className="priceHeader">Free</div>
              <div className="priceAmount">$0</div>
              <ul>
                <li>Access to basic templates</li>
                <li>5 free generations per month</li>
                <li>Basic download & copy features</li>
              </ul>
            </div>
            <div className="priceCard">
              <div className="priceHeader">Pro</div>
              <div className="priceAmount">$9 / mo</div>
              <ul>
                <li>Unlimited generations</li>
                <li>Resume personalization and extraction</li>
                <li>Priority support and PDF downloads</li>
              </ul>
            </div>
            <div className="priceCard">
              <div className="priceHeader">Team</div>
              <div className="priceAmount">Contact</div>
              <ul>
                <li>Multi-seat management</li>
                <li>Centralized billing</li>
                <li>Dedicated support</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <main ref={mainRef} className="container">
        <div className="grid">
          <section className="panel panelGlass">
            <h2 className="panelTitle">Generate a cover letter</h2>

            <Form form={form} setForm={setForm} onGenerate={onGenerate} onReset={onReset} disabled={loading} />

            <div className="divider" />

            <ResumeUpload onExtract={(text) => setResumeText(text)} disabled={loading} />

            {loading ? (
              <div className="loadingWrap">
                <Loading />
                <div className="loadingText">Generating Cover Letter...</div>
              </div>
            ) : null}

            {error ? <div className="errorBox">{error}</div> : null}
            {success ? <div className="successBox">{success}</div> : null}

            {toast ? (
              <div className={`toast ${toast.type === 'error' ? 'toastError' : 'toastSuccess'}`}>{toast.message}</div>
            ) : null}
          </section>

          <section className="resultPanel">
            <CoverLetter
              coverLetter={coverLetter}
              onCopy={onCopy}
              onDownloadPDF={onDownloadPDF}
              disabled={!coverLetter.trim()}
            />
          </section>
        </div>
      </main>

      <footer className="footer">Built with React, Express, and Gemini API.</footer>
    </div>
  );
}

