import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import Form from './components/Form.jsx';
import CoverLetter from './components/CoverLetter.jsx';
import Loading from './components/Loading.jsx';
import ResumeUpload from './components/ResumeUpload.jsx';


function clampWords(text) {
  return text
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean);
}

export default function App() {
  const [darkMode, setDarkMode] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [coverLetter, setCoverLetter] = useState('');
  const [toast, setToast] = useState(null);
  const [resumeText, setResumeText] = useState('');

  const initialForm = useMemo(
    () => ({
      name: '',
      email: '',
      role: '',
      company: '',
      skills: '',
      experience: '',
      education: ''
    }),
    []
  );

  const [form, setForm] = useState(initialForm);

  useEffect(() => {
    const stored = window.localStorage.getItem('clg_dark_mode');
    if (stored === '1') setDarkMode(true);
  }, []);

  useEffect(() => {
    window.localStorage.setItem('clg_dark_mode', darkMode ? '1' : '0');
    document.documentElement.dataset.theme = darkMode ? 'dark' : 'light';
  }, [darkMode]);

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), 2600);
    return () => clearTimeout(t);
  }, [toast]);

  async function onGenerate() {
    setError('');
    setSuccess('');
    setLoading(true);

    try {
      const payload = {
        name: form.name,
        role: form.role,
        company: form.company,
        skills: form.skills,
        experience: form.experience,
        education: form.education,
        // optional
        resumeText: resumeText || undefined
      };

      // Phase 1 fallback template generation (works without Gemini)
      // If backend is available and Gemini is correctly configured, we’ll still try it.
      const template =
        `Dear Hiring Manager,\n\n` +
        `I am excited to apply for the ${form.role} position at ${form.company}. My experience in ${form.experience} and my skills in ${form.skills} make me a strong match for your team.\n\n` +
        `In my previous work, I have delivered results including: (1) improving performance and outcomes, (2) collaborating across teams, and (3) communicating clearly with stakeholders. I am confident that I can bring the same impact to ${form.company}.\n\n` +
        `I would welcome the opportunity to discuss how my background aligns with your needs. Thank you for your time and consideration.\n\n` +
        `Sincerely,\n` +
        `${form.name}`;

      try {
        const res = await axios.post('/generate', payload);
        const aiText = res.data?.coverLetter;
        if (aiText && typeof aiText === 'string' && aiText.trim()) {
          setCoverLetter(aiText.trim());
          setToast({ type: 'success', message: 'Cover letter generated by AI.' });
        } else {
          setCoverLetter(template);
          setToast({ type: 'success', message: 'Cover letter generated (template fallback).' });
        }
      } catch {
        setCoverLetter(template);
        setToast({ type: 'success', message: 'Cover letter generated (template fallback).' });
      }
    } catch (e) {
      const msg = e?.response?.data?.error || e?.message || 'Failed to generate. Please try again.';
      // Don’t hard-fail the UI—show template fallback if Gemini is unreachable.
      setError(msg);
      setToast({ type: 'error', message: 'Gemini generation failed. Using template instead.' });
    } finally {
      setLoading(false);
    }
  }

  async function onCopy() {
    if (!coverLetter.trim()) return;
    try {
      await navigator.clipboard.writeText(coverLetter);
      setSuccess('Copied to clipboard!');
      setToast({ type: 'success', message: 'Copied to clipboard.' });
    } catch {
      setError('Copy failed. Please copy manually.');
      setToast({ type: 'error', message: 'Copy failed.' });
    }
  }

  function onReset() {
    setForm(initialForm);
    setCoverLetter('');
    setResumeText('');
    setError('');
    setSuccess('');
    setToast({ type: 'success', message: 'Form reset.' });
  }

  function onDownloadPDF() {
    // Simple, client-only PDF: uses print-to-PDF via a temporary window.
    // Production apps may use a dedicated PDF generator library.
    const w = window.open('', '_blank');
    if (!w) {
      setError('Popup blocked. Please allow popups to download PDF.');
      setToast({ type: 'error', message: 'Popup blocked.' });
      return;
    }

    const escapeHtml = (s) =>
      (s || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '<')
        .replace(/>/g, '>');

    const words = clampWords(coverLetter).length;

    w.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>Cover Letter</title>
      <style>
        body{font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; padding:40px; color:#111;}
        .box{border:1px solid #e5e7eb; border-radius:14px; padding:28px;}
        h1{font-size:18px; margin:0 0 14px 0;}
        pre{white-space:pre-wrap; word-break:break-word; font-family:inherit; line-height:1.4;}
        .meta{color:#6b7280; font-size:12px; margin-bottom:14px;}
      </style></head><body>
      <div class="box">
        <h1>AI Cover Letter</h1>
        <div class="meta">Word count: ${words}</div>
        <pre>${escapeHtml(coverLetter)}</pre>
      </div>
      <script>setTimeout(()=>{window.print();}, 250);</script>
      </body></html>`);
    w.document.close();
  }

  return (
    <div className="app">
      <header className="topbar">
        <div className="brand">
          <div className="logo" />
          <div>
            <div className="brandTitle">CoverLetter AI</div>
            <div className="brandSubtitle">ATS-friendly cover letters</div>
          </div>
        </div>

        <div className="topbarActions">
          <button
            className="iconBtn"
            onClick={() => setDarkMode((v) => !v)}
            aria-label="Toggle dark mode"
            type="button"
          >
            {darkMode ? '🌙 Dark' : '☀️ Light'}

          </button>
        </div>
      </header>

      <main className="container">
        <div className="grid">
          <section className="panel panelGlass">
            <h2 className="panelTitle">Generate a cover letter</h2>

            <Form form={form} setForm={setForm} onGenerate={onGenerate} onReset={onReset} disabled={loading} />

            <div className="divider" />

            <ResumeUpload onExtract={(text) => setResumeText(text)} disabled={loading} />

            {loading ? (
              <div className="loadingWrap">
                <Loading />
                <div className="loadingText">Generating Cover Letter...</div>
              </div>
            ) : null}

            {error ? <div className="errorBox">{error}</div> : null}
            {success ? <div className="successBox">{success}</div> : null}

            {toast ? (
              <div className={`toast ${toast.type === 'error' ? 'toastError' : 'toastSuccess'}`}>{toast.message}</div>
            ) : null}
          </section>

          <section className="resultPanel">
            <CoverLetter
              coverLetter={coverLetter}
              onCopy={onCopy}
              onDownloadPDF={onDownloadPDF}
              disabled={!coverLetter.trim()}
            />
          </section>
        </div>
      </main>

      <footer className="footer">Built with React, Express, and Gemini API.</footer>
    </div>
  );
}

